-- CareerAI initial schema
-- Apply only after reviewing and testing in a non-production Supabase project.
-- Seed role/skill/question rows from data/*.csv separately.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  branch text,
  study_year smallint check (study_year between 1 and 8),
  hours_per_week numeric(5,2) check (hours_per_week is null or hours_per_week between 0 and 168),
  preferred_roles text[] not null default '{}',
  location_preference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  description text not null,
  active boolean not null default true
);

create table if not exists public.career_roles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  level text not null default 'entry',
  description text not null,
  source_label text not null,
  source_url text,
  source_checked_at date,
  version text not null,
  active boolean not null default true
);

create table if not exists public.role_skills (
  role_id bigint not null references public.career_roles(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  target_level smallint not null check (target_level between 1 and 4),
  importance smallint not null check (importance between 1 and 3),
  prerequisite_order smallint not null default 1 check (prerequisite_order >= 1),
  rationale text not null,
  version text not null,
  primary key (role_id, skill_id, version)
);

create table if not exists public.assessment_questions (
  id text primary key,
  skill_id bigint not null references public.skills(id) on delete restrict,
  category text not null,
  prompt text not null,
  options_json jsonb not null,
  answer_key text not null,
  explanation text not null,
  difficulty text not null default 'easy',
  version text not null,
  active boolean not null default true
);

create table if not exists public.assessment_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  version text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.assessment_answers (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references public.assessment_attempts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null references public.assessment_questions(id) on delete restrict,
  selected_key text,
  is_correct boolean,
  answered_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

create table if not exists public.skill_observations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete restrict,
  value numeric(4,2) check (value is null or value between 0 and 4),
  scale_max numeric(4,2) not null default 4 check (scale_max > 0),
  source text not null check (source in ('diagnostic', 'self_report', 'self_attested_project', 'reviewed_project')),
  evidence_note text,
  confidence text not null default 'medium' check (confidence in ('high', 'medium', 'needs_more_evidence')),
  rubric_version text not null,
  observed_at timestamptz not null default now()
);

create table if not exists public.roadmaps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.career_roles(id) on delete restrict,
  role_version text not null,
  hours_per_week numeric(5,2) not null check (hours_per_week between 0 and 168),
  status text not null default 'active' check (status in ('active', 'paused', 'complete', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roadmap_tasks (
  id uuid primary key default gen_random_uuid(),
  roadmap_id uuid not null references public.roadmaps(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_number smallint not null check (week_number >= 1),
  title text not null,
  description text not null,
  deliverable text not null,
  estimated_hours numeric(5,2) not null check (estimated_hours >= 0),
  prerequisite_task_id uuid references public.roadmap_tasks(id) on delete set null,
  resource_url text,
  status text not null default 'todo' check (status in ('todo', 'in_progress', 'done', 'blocked')),
  completed_at timestamptz
);

create table if not exists public.resume_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Untitled resume',
  raw_text text not null check (char_length(raw_text) <= 50000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resume_analyses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  resume_id uuid not null references public.resume_documents(id) on delete cascade,
  role_id bigint references public.career_roles(id) on delete set null,
  job_text text not null check (char_length(job_text) <= 50000),
  keyword_score smallint check (keyword_score is null or keyword_score between 0 and 100),
  coverage numeric(5,2) check (coverage is null or coverage between 0 and 100),
  result_json jsonb not null,
  model_label text not null default 'deterministic-fallback',
  created_at timestamptz not null default now()
);

create table if not exists public.interview_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint references public.career_roles(id) on delete set null,
  mode text not null check (mode in ('behavioural', 'technical')),
  question_id text references public.assessment_questions(id) on delete set null,
  question_text text not null,
  answer_text text check (answer_text is null or char_length(answer_text) <= 20000),
  rubric_result_json jsonb,
  model_label text not null default 'deterministic-fallback',
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  payload_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_skill_observations_user on public.skill_observations(user_id, skill_id);
create index if not exists idx_roadmaps_user on public.roadmaps(user_id, status);
create index if not exists idx_tasks_user on public.roadmap_tasks(user_id, roadmap_id, status);
create index if not exists idx_resume_user on public.resume_documents(user_id, updated_at desc);
create index if not exists idx_events_user_time on public.events(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists roadmaps_set_updated_at on public.roadmaps;
create trigger roadmaps_set_updated_at before update on public.roadmaps for each row execute function public.set_updated_at();
drop trigger if exists resumes_set_updated_at on public.resume_documents;
create trigger resumes_set_updated_at before update on public.resume_documents for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.career_roles enable row level security;
alter table public.role_skills enable row level security;
alter table public.assessment_questions enable row level security;
alter table public.assessment_attempts enable row level security;
alter table public.assessment_answers enable row level security;
alter table public.skill_observations enable row level security;
alter table public.roadmaps enable row level security;
alter table public.roadmap_tasks enable row level security;
alter table public.resume_documents enable row level security;
alter table public.resume_analyses enable row level security;
alter table public.interview_sessions enable row level security;
alter table public.events enable row level security;

-- Public seed/read-only data. Grant only the operations the UI needs.
create policy "authenticated users read active skills" on public.skills for select to authenticated using (active = true);
create policy "authenticated users read active roles" on public.career_roles for select to authenticated using (active = true);
create policy "authenticated users read role skills" on public.role_skills for select to authenticated using (true);
create policy "authenticated users read active questions" on public.assessment_questions for select to authenticated using (active = true);

create policy "users read own profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "users delete own profile" on public.profiles for delete to authenticated using (auth.uid() = id);

create policy "users own assessment attempts" on public.assessment_attempts for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own assessment answers" on public.assessment_answers for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own observations" on public.skill_observations for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own roadmaps" on public.roadmaps for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own roadmap tasks" on public.roadmap_tasks for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own resumes" on public.resume_documents for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own resume analyses" on public.resume_analyses for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own interview sessions" on public.interview_sessions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own events" on public.events for insert to authenticated with check (auth.uid() = user_id);
create policy "users read own events" on public.events for select to authenticated using (auth.uid() = user_id);
